### ISSUE TITLE
remove_unpainted_shapes should drop 0 area unstroked

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#157]
`<rect x="-1228" y="-57.67" style="fill:#F2F2F2;" width="0" height="0.67"/>` should be dropped by remove_unpainted_shapes; 0 area and no stroke

**Comment by rsheeter** [comment]
pathops has a method for area. Use that; bounding box of two diagonal points [which wouldn't paint anything unless stroked] would have an area.

**Comment by anthrotype** [comment]
this https://github.com/fonttools/skia-pathops/blob/38c6af86522a424ff637f805aaefe74b7e0c2137/src/python/pathops/_pathops.pyx#L905

**Comment by anthrotype** [comment]
the area is exposed to python as `Pathops.area` property.
the area is a signed value, depends on the contour direction (negative for clockwise, positive for counter-clockwise).
I think it is possible that a path self-intersects and yields an area of 0 (imagine infinite symbol ♾️ that loops onto itself), because the two parts can cancel out each other.
We can still use the area != 0 to test if the path might paint, but we first need to di a Path.simplify() (aka "removing overlaps") before computing the area; that way, the will no longer have self-intersections that flip the direction and may zero out the area.

**Comment by anthrotype** [comment]
ah! I just remembered. We actually don't need to mess with area at all. Simply doing `Path.simplify()` will get rid of all unpaintable paths. A simplified path is one that does not have any of such unpaintable, invisible subpaths. Thanks Skia

**Comment by anthrotype** [comment]
picosvg's SVGPath already does that in its `remove_overlaps()` method

**Comment by anthrotype** [comment]
currently we only run `remove_overlaps` for the paths that have fill-rule="evenodd". I'm not suggesting that we do for all paths unconditionally, that would be unnecessary. But we can run that inside SVGShape.might_paint() on a copy of self and _then_ test if the resulting path is empty.
