### ISSUE TITLE
Group opacity with overlapping shapes is not handled well

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#78]
`picosvg` an svg that uses group opacity and render before/after. They may look quite dissimilar. 

*Sample 1*

Input:
```svg
<svg viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg">
  <rect x="24" y="16" width="32" height="112"/>
  <g opacity="0.6">
     <path fill="red" d="M10,30 H100 V120 H10 V30 z"/>
     <path fill="blue" d="M5,25 L105,25 L105,125 L5,125 Z M15,35 L15,115 L95,115 L95,35 Z"/>
  </g>
</svg>
```

<img width="463" alt="Screen Shot 2020-08-10 at 2 02 10 PM" src="https://user-images.githubusercontent.com/6466432/89831072-18314d80-db12-11ea-906f-bfe5fb4f5343.png">

*Sample 2*

Input
```svg
<svg viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg">
  <rect x="24" y="16" width="32" height="112" />
  <g opacity="0.7">
     <path fill="red" d="M10,30 H100 V120 H10 V30 z"/>
     <path fill="blue" d="M5,25 L105,25 L105,125 L5,125 Z M15,35 L15,115 L95,115 L95,35 Z"/>
     <g opacity="0.8">
        <path fill="yellow" d="M24,67 c-45,-45 45,-45 0,0 c-45,45 45,45 0,0 z" opacity="0.5"/>
        <path fill="green" d="M10,64 64,32 64,96 Z"/>
     </g>
     <path fill="green" d="M128,64 64,32 64,96  Z"/>
  </g>
</svg>
```

<img width="564" alt="Screen Shot 2020-08-10 at 2 02 31 PM" src="https://user-images.githubusercontent.com/6466432/89831110-241d0f80-db12-11ea-8218-8fc7cdac6fb7.png">

**Comment by anthrotype** [comment]
COLRv1 spec and implementation now support alpha channel masking for a group of layers through a `PaintComposite` table that has a semi-transparent black PaintSolid in the source sub-graph, the group of layers (as `PaintColrGlyph` or `PaintColrLayers`) in the backdrop sub-graph, composed together via the `Source In` mode (see figure 5.40 in https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md).

So, in order to support SVG group-level opacity in our COLRv1 build pipeline, we need to:

1) in picosvg, _not_ remove groups `<g>` elements that have some interesting `opacity` attribute and contain more than one children
2) in nanoemoji, translate these constructs into equivalent PaintComposite composing (`SRC_IN` mode) an opaque black PaintSolid (src) with PaintColrLayers representing the list of paths (backdrop).

@rsheeter is this analysis correct?
